### ISSUE TITLE
Unable to upload using SE tools

### ISSUE THREAD

**Issue by automatiek** [alifsemi/alif_M55-viewfinder#3]
`app-gen` tools expect a binary file https://github.com/alifsemi/alif_M55-viewfinder/blob/d79821d168ffed5472a37dd897e28cda7c90f713/.vscode/tasks.json#L83

Conversion from `.elf` to `.bin` is missing.

**Comment by AkiMakkonen-AlifSemi** [comment]
Most likely you have not followed the Getting Started Guide for setting up the environment:
https://alifsemi.com/download/AUGD0012

I just verified that the .bin is generated and can be programmed. Please note that we use old quite old cmsis-toolbox and newer ones will not work. This is also something that we want to fix with the new template. Sorry for the inconvenience.
